### ISSUE TITLE
Transfering data from python to matlab on windows

### ISSUE THREAD

**Issue by eladnoor** [eladnoor/component-contribution#11]
When running the script prepare_training_data.py on a windows machine, the resulting file ( training_data_matlab.mat) is not readable in Matlab.
The same script works well on Linux and the resulting file can be read in Matlab on both platforms.

**Comment by eladnoor** [comment]
The source of this bug was the implementation of scipy.io.savemat on windows, which doesn't work well when the input is a file handle (rather than a file name). Therefore, the bug was fixed by using file names exclusively (which works well both on Windows and Linux). OSX untested.

**Comment by 3point1415** [comment]
Why am I receiving these notifications?
