### ISSUE TITLE
New compounds with fake KEGG ids won't get cached

### ISSUE THREAD

**Issue by serdar-** [eladnoor/component-contribution#17]
When I add new components to `kegg_additions.tsv` and rerun the `compound_cacher.py`, I cannot obtain the compound information with the KEGG id. I think `compound_casher.py` does not read the entries for new components. Could you suggest a workaround for this problem? Many thanks in advance!

**Comment by eladnoor** [comment]
It seems that the issue is specific to Jupyter notebooks, but was not reproduced in standard python scripts.
