### ISSUE TITLE
Use SQLite for the compound cache instead of CSV

### ISSUE THREAD

**Issue by eladnoor** [eladnoor/component-contribution#33]

**Comment by eladnoor** [comment]
An initial implementation has been made, but we should use SQLite more intelligently as the memory cache itself (i.e. update the DB every time a new compound is cached rather than when dump() is called explicitly).

**Comment by flamholz** [comment]
pandas works just fine for this purpose as well - it can read csv files and
you can query it like a DB.
A

**Comment by eladnoor** [comment]
In the future, I would like to cache a large amount of compounds (hundreds of thousands perhaps), including their structure, pKas, group vectors, etc. I'm not sure that we will be able to hold all that data in memory at once.

**Comment by flamholz** [comment]
Got it
